apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterRestore
metadata:
  name: on-demand-backup-pvc-bsource
spec:
  pxcCluster: some-name
  backupSource:
    destination: pvc/xb-on-demand-backup-pvc-bsource
    storageName: pvc
